turbine: "osw_15MW"
installation_availability: 0.7 # 30% downtime during installation to match ORCA
site:
  area: 142 # km^2
  depth: 905 # m - this value is overridden by greenheart config
  distance: 41.7896843 # km
  distance_to_landfall: 40.92311859 # km
  mean_windspeed: False # required input for ORBIT, provide desired mean wind speed or set to False to give ORBIT the mean wind speed from the lat/lon selection
plant:
  capacity: 990 # MW
  layout: grid
  num_turbines: 66 # needs to be changed based on turbine model - this value is overridden by greenheart config
  row_spacing: 7 # rotor diameters # based on rule of thumb of 7D - this value is overridden by greenheart config
  substation_distance: 1 # from ORBIT/examples/configs/example_fixed_project.yaml
  turbine_spacing: 7 # rotor diameters # original 10 - this value is overridden by greenheart config
landfall:
  interconnection_distance: 5 # km
  trench_length: 4 # km

# Vessels
array_cable_install_vessel: example_cable_lay_vessel # from ORBIT/examples/configs/example_fixed_project.yaml
export_cable_install_vessel: example_cable_lay_vessel
# Assume the dynamic cables will be suspended in the water column (not buried)
mooring_install_vessel: example_support_vessel
ahts_vessel: example_ahts_vessel
oss_install_vessel: example_support_vessel # assume that this is towed out with a anchor handling vessel
support_vessel: example_support_vessel
towing_vessel: example_towing_vessel
towing_vessel_groups:
  ahts_vessels: 1
  station_keeping_vessels: 1
  towing_vessels: 2
  num_groups: 3 # note these numbers are different than the default for ORBIT- I believe ORCA assumes only one installation group of 3 vessels total for floating

# Module Specific
OffshoreSubstationInstallation:
  feeder: floating_barge
array_system:
  free_cable_length: 0.5
array_system_design:
  cables:
  - XLPE_185mm_66kV_dynamic # Use dynamic cabling for floating
  - XLPE_630mm_66kV_dynamic
export_system_design:
  cables:
  - XLPE_1000mm_220kV_dynamic #HVAC
  # - HVDC_2000mm_320kV_dynamic # HVDC lines
  percent_added_length: 0.1
mooring_system_design:
  num_lines: 3
  drag_embedment_fixed_length: 0
  anchor_type: Drag Embedment
  mooring_type: Semitaut
# Configured Phases

design_phases:
- ArraySystemDesign # from ORBIT/examples/configs/example_floating_project.yaml
- ElectricalDesign 
- MooringSystemDesign
- OffshoreFloatingSubstationDesign
- SemiSubmersibleDesign # from ORBIT/examples/configs/example_floating_project.yaml
install_phases:
  ExportCableInstallation: 0
  MooringSystemInstallation: 0
  MooredSubInstallation: !!python/tuple
  - MooringSystemInstallation
  - 0.5 # Start substructure install when 50% of mooring lines installed
  ArrayCableInstallation: !!python/tuple
  - MooredSubInstallation
  - 0.5 # Start array cable installation when 50% of floaters are installed
  
  # OffshoreSubstationInstallation: !!python/tuple
  FloatingSubstationInstallation: !!python/tuple
  - ExportCableInstallation
  - 0.25 # Start OSS installation when 25% of cable installation is complete

substation_design:
  floating_oss: True
semisubmersible_design:
  stiffened_column_CR: 7000
substructure:
  takt_time: 168

# Wind Project Inputs
project_parameters:
  turbine_capex: 1500 # $USD turbine CAPEX only as per discussion with Matt Shields 
  opex_rate: 47.29652759 #osw national analysis, $USD/kW/yr ATB 2022, OpEx based on R&D assumptions with a base year of 2022. ATB https://atb.nrel.gov/electricity/2022/offshore_wind