site:
  mean_windspeed: False 
  depth: 0 #m
  wind_layout:
    row_spacing: 7  # Also defined in ORBIT config for offshore layout. Greenheart config values override the values in ORBIT.
    turbine_spacing: 7 # Also defined in ORBIT config for offshore layout. Greenheart config values override the values in ORBIT.
    grid_angle: 0 # wind layout grid angle in degrees where 0 is north, increasing clockwise
    row_phase_offset: 0 # wind layout offset of turbines along row from one row to the next
project_parameters:
  project_lifetime: 30
  grid_connection: False # option, can be turned on or off
  ppa_price: 0.025 # $/kWh based on 2022 land based wind market report (ERCOT area ppa prices) https://www.energy.gov/sites/default/files/2022-08/land_based_wind_market_report_2202.pdf
  hybrid_electricity_estimated_cf: 0.492 #should equal 1 if grid_connection = True
  atb_year: 2030
  cost_year: 2022
  installation_time: 36 # months
finance_parameters:
  costing_general_inflation: 0.025 # used to adjust modeled costs to cost_year
  profast_general_inflation: 0.0 # 0 for nominal analysis
  discount_rate: 0.09 # nominal return based on 2024 ATB basline workbook for land-based wind
  debt_equity_split: False
  debt_equity_ratio: 2.62 # 2024 ATB uses 72.4% debt for land-based wind
  property_tax: 0.02 # https://www.house.mn.gov/hrd/issinfo/clsrates.aspx
  property_insurance: 0.01 # percent of CAPEX estimated based on https://www.nrel.gov/docs/fy25osti/91775.pdf
  total_income_tax_rate: 0.308 # 0.257 tax rate in 2024 atb baseline workbook, value here is based on federal (21%) and state in MN (9.8)
  capital_gains_tax_rate: 0.15 # H2FAST default
  sales_tax_rate: 0.07375 # total state and local sales tax in St. Louis County https://taxmaps.state.mn.us/salestax/
  debt_interest_rate: 0.07 # based on 2024 ATB nominal interest rate for land-based wind
  debt_type: "Revolving debt" # can be "Revolving debt" or "One time loan". Revolving debt is H2FAST default and leads to much lower LCOH
  loan_period: 0 # H2FAST default, not used for revolving debt
  cash_onhand_months: 1 # H2FAST default
  administrative_expense_percent_of_sales: 0.00 # percent of sales H2FAST default
  depreciation_method: "MACRS" # can be "MACRS" or "Straight line" - MACRS may be better and can reduce LCOH by more than $1/kg and is spec'd in the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
  depreciation_period: 5 # years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
  depreciation_period_electrolyzer: 7 # based on PEM Electrolysis H2A Production Case Study Documentation estimate of 7 years. also see https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
  discount_years:
    wind: 2022 # Updated for GS
    wind_and_electrical: 2020 # Updated for GS
    wave: 2020
    solar: 2022 # Updated for GS
    battery: 2022 # Updated for GS
    platform: 2022 # TODO ask Nick and Charlie
    electrical_export_system: 2022 # also from ORBIT, so match wind assumptions. TODO ask Sophie Bradenkamp
    desal: 2013 # from code citation: https://www.nrel.gov/docs/fy16osti/66073.pdf
    electrolyzer: 2022 # for values used in hybrid system reference designs
    h2_transport_compressor: 2016 # listed in code header
    h2_storage:
      pressure_vessel: 2022 # based on readme for Compressed_gas_function
      pipe: 2019 # Papadias 2021
      salt_cavern: 2019 # Papadias 2021
      turbine: 2003 # assumed based on Kottenstette 2004
      lined_rock_cavern: 2018 # based on Papadias 2021 and HD SAM
      none: 2022 # arbitrary
    h2_pipe_array: 2018 # ANL costs
    h2_transport_pipeline: 2018 # same model for costs as the h2_pipe_array
  wind:
    expected_plant_cost: 'none'
electrolyzer:
  sizing:
    resize_for_enduse: False
    size_for: 'BOL' #'BOL' (generous) or 'EOL' (conservative)
    hydrogen_dmd: 
  rating: 1125.165 # MW 
  cluster_rating_MW: 40
  pem_control_type: 'basic'
  eol_eff_percent_loss: 13 #eol defined as x% change in efficiency from bol
  uptime_hours_until_eol: 77600 #number of 'on' hours until electrolyzer reaches eol
  include_degradation_penalty: True #include degradation
  turndown_ratio: 0.1 #turndown_ratio = minimum_cluster_power/cluster_rating_MW
  electrolyzer_capex: 2000 # $/kW overnight installed capital costs for a 1 MW system in 2022 USD/kW (DOE hydrogen program record 24005	Clean Hydrogen Production Cost Scenarios with PEM Electrolyzer Technology 05/20/24) (https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/24005-clean-hydrogen-production-cost-pem-electrolyzer.pdf?sfvrsn=8cb10889_1) 
  replacement_cost_percent: 0.15 # percent of capex - H2A default case
  cost_model: "singlitico2021" # "basic" is a basic cost model based on H2a and HFTO program record for PEM electrolysis. "singlitico2021" uses cost estimates from that paper
h2_transport_compressor:
  outlet_pressure: 68 # bar based on HDSAM
h2_storage_compressor:
  output_pressure: 100 # bar (1 bar = 100 kPa)
  flow_rate: 89 # kg/hr
  energy_rating: 802 # kWe (aka 1 kWh)
  mean_days_between_failures: 200 # days
h2_transport_pipe:
  outlet_pressure: 10 # bar - from example in code from Jamie #TODO check this value
h2_storage:
  size_capacity_from_demand:
    flag: True # If True, then storage is sized to provide steady-state storage    
  capacity_from_max_on_turbine_storage: False # if True, then days of storage is ignored and storage capacity is based on how much h2 storage fits on the turbines in the plant using Kottenstete 2003.
  type: "lined_rock_cavern" # can be one of ["none", "pipe", "turbine", "pressure_vessel", "salt_cavern", "lined_rock_cavern"]  
  days: 0 #how many days worth of production we should be able to store (this is ignored if `capacity_from_max_on_turbine_storage` is set to True)

policy_parameters: # these should be adjusted for inflation prior to application - order of operations: rate in 1992 $,
#then prevailing wage multiplier if applicable, then inflation
  option1: # base # no policy included ---> see files/task1/regulation and policy revue/ page 4 of 13 middle - read this
  # and look at assumptions
    electricity_itc: 0
    electricity_ptc: 0
    h2_ptc: 0
    h2_storage_itc: 0
  option2: # base credit levels with H2
    electricity_itc: 0
    electricity_ptc: 0.003 # $0.003/kW (this is base, see inflation adjustment in option 3)
    h2_ptc: 0.6 # $0.60/kg h2 produced - assumes net zero but not meeting prevailing wage requirements - does this need to be
    # adjusted for inflation from 2022 dollars to claim date, probably constant after claim date?
    h2_storage_itc: 0.06
  option3: # same as option 5, but assuming prevailing wages are met --> 5x multiplier on both PTCs
    electricity_itc: 0
    electricity_ptc: 0.015 # $/kWh 1992 dollars
    h2_ptc: 3.00 # $/kg 2022 dollars - do not adjust for inflation
    h2_storage_itc: 0.3
  # bonus options, option 5 and 6 but ITC equivalents
  option4: # prevailing wages not met
    electricity_itc: 0.06 # %/100 capex
    electricity_ptc: 0.00 # $/kW 1992 dollars
    h2_ptc: 0.6 # $0.60/kg produced 2022 dollars - assumes net zero but not meeting prevailing wage requirements - does this need to be
    # do not adjust for inflation, probably constant after claim date?
    h2_storage_itc: 0.06
  option5: # prevailing wages met
    electricity_itc: 0.30 # %/100 capex
    electricity_ptc: 0.0 # $/kWh 1992 dollars
    h2_ptc: 3.00 # $/kg of h2 produced 2022 dollars - do adjust for inflation every year applied and until application year
    h2_storage_itc: 0.3
  option6: # assumes prevailing wages are met, and includes 10% bonus credit of domestic content (100% of steel and iron
  # and mfg. components from the US)
    electricity_itc: 0.40 # %/100 capex
    electricity_ptc: 0.0 # $/kWh 1992 dollars
    h2_ptc: 3.00 # $/kg of h2 produced 2022 dollars - do adjust for inflation every year applied and until application year
    h2_storage_itc: 0.4
  option7: # assumes prevailing wages are met, and includes 10% bonus credit of domestic content (100% of steel and iron
  # and mfg. components from the US)
    electricity_itc: 0.0 # %/100 capex
    electricity_ptc: 0.0165 # $/kWh 1992 dollars (0.015*1.1)
    h2_ptc: 3.00 # $/kg of h2 produced 2022 dollars - do adjust for inflation every year applied and until application year
  # you can elect itc_for_h2 in leu of the h2_ptc - this choice is independent of the other tech credit selections
    # 6% or %50 for itc_for_h2
    h2_storage_itc: 0.5

plant_design:
  scenario1:
    electrolyzer_location: "onshore" # can be one of ["onshore", "turbine", "platform"]
    transportation: "colocated" # can be one of ["hvdc", "pipeline", "none", hvdc+pipeline, "colocated"]
    h2_storage_location: "onshore" # can be one of ["onshore", "turbine", "platform"]
    wind_location: "onshore" # can be one of ["onshore", "offshore"]
    pv_location: "onshore" # can be one of ["none", "onshore", "platform"]
    battery_location: "onshore" # can be one of ["none", "onshore", "platform"]

steel:
  capacity:
    input_capacity_factor_estimate: 0.9
  costs:
    operational_year: 2030
    o2_heat_integration: false
    feedstocks:
      oxygen_market_price: 0.0 # 0.03 $/kgO2 if `o2_heat_integration` == 1
      excess_oxygen: 395
      lime_unitcost: 108 #2022 USD/tonne lime
      lime_transport_cost: 47.72 # 2022 USD/tonne lime
      carbon_unitcost: 205 # 2022 USD/tonne carbon
      carbon_transport_cost: 64.91 # 2022 USD/tonne carbon
      electricity_cost: 101 # 2022 USD - not actually used in cost/finance model
      iron_ore_pellet_unitcost: 224.63 # 2022 USD/tonne iron
      iron_ore_pellet_transport_cost: 0.63 # 2022 USD/tonne iron
      raw_water_unitcost: 0.64036495572 # 2022 USD/tonne
      iron_ore_consumption: 1.62927
      raw_water_consumption: 0.80367
      lime_consumption: 0.01812
      carbon_consumption: 0.0538
      hydrogen_consumption: 0.06596
      natural_gas_consumption: 0.71657
      electricity_consumption: 0.5502
      slag_disposal_unitcost: 41 # 2022 USD/tonne
      slag_production: 0.17433 # 2022 USD
      maintenance_materials_unitcost: 8.34 # 2022 USD
      natural_gas_prices:
        "2030":	3.550978
        "2031":	3.64287
        "2032":	3.729118
        "2033":	3.863692
        "2034":	3.968392
        "2035":	4.063583
        "2036":	4.078393
        "2037":	4.11822
        "2038":	4.223948
        "2039":	4.175323
        "2040":	4.278972
        "2041":	4.349604
        "2042":	4.338836
        "2043":	4.28955
        "2044":	4.238549
        "2045":	4.215838
        "2046":	4.188734
        "2047":	4.15333
        "2048":	4.118717
        "2049":	4.079817
        "2050":	4.067735
        "2051":	4.067735
        "2052":	4.067735
        "2053":	4.067735
        "2054":	4.067735
        "2055":	4.067735
        "2056":	4.067735
        "2057":	4.067735
        "2058":	4.067735
        "2059":	4.067735
  finances:
    plant_life: 30
    grid_prices:
      "2030": 86.75938078
      "2031": 89.63484012400001
      "2032": 92.510299468
      "2033": 95.385758812
      "2034": 98.261218156
      "2035": 101.1366775
      "2036": 101.76581348
      "2037": 102.39494946
      "2038": 103.02408544
      "2039": 103.65322142
      "2040": 104.2823574
      "2041": 101.645291536
      "2042": 99.00822567200001
      "2043": 96.371159808
      "2044": 93.734093944
      "2045": 91.09702808
      "2046": 92.047049024
      "2047": 92.997069968
      "2048": 93.94709091200001
      "2049": 94.897111856
      "2050": 95.8471328
      "2051": 95.8471328
      "2052": 95.8471328
      "2053": 95.8471328
      "2054": 95.8471328
      "2055": 95.8471328
      "2056": 95.8471328
      "2057": 95.8471328
      "2058": 95.8471328
      "2059": 95.8471328


    # Additional parameters passed to ProFAST
    financial_assumptions:
      "total income tax rate": 0.2574
      "capital gains tax rate": 0.15
      "leverage after tax nominal discount rate": 0.10893
      "debt equity ratio of initial financing": 0.624788
      "debt interest rate": 0.050049


opt_options:
  opt_flag: True
  general: 
    folder_output: "output"
    fname_output: "test_run_greenheart_optimization"
  design_variables:
    electrolyzer_rating_kw:
      flag: True
      lower: 900000.0
      upper: 1300000.0
      units: "kW"
    pv_capacity_kw:
      flag: True
      lower: 1200000.0
      upper: 1800000.0
      units: "kW"
    wave_capacity_kw:
      flag: False
      lower: 1000.0
      upper: 2000000.0
      units: "kW"
    battery_capacity_kw:
      flag: True
      lower: 300000.0
      upper: 450000.0
      units: "kW"
    battery_capacity_kwh:
      flag: True
      lower: 300000.0
      upper: 450000.0
      units: "kW*h"
    turbine_x:
      flag: False
      lower: 0.0
      upper: 20000.0
      units: "m"
    turbine_y:
      flag: False
      lower: 0.0
      upper: 20000.0
      units: "m"
  constraints:
    turbine_spacing:
      flag: False
      lower: 0.0
    boundary_distance:
      flag: False
      lower: 0.0
    pv_to_platform_area_ratio:
      flag: False 
      upper: 1.0 # relative size of solar pv area to platform area
    user: {}
  merit_figure: "lcos"
  merit_figure_user:
    name: "lcos"
    max_flag: False
    ref: 1.0 # value of objective that scales to 1.0
  driver:
    # optimization:
    #   flag: True
    #   solver: "COBYLA"
    #   maxiter: 200
    #   debug_print: False
    #   time_limit: 3500
    #   step_calc: None
    #   form: "forward"
    optimization:
      flag: False
      solver: "SNOPT"
      tol: 1E-8
      max_major_iter: 200
      max_minor_iter: 400
      time_limit: 72000 # (sec) optional
      # "hist_file_name: "snopt_history.txt", # optional
      verify_level: 0 # optional
      step_calc: "None"
      form: "central" # type of finite differences to use, can be one of ["forward", "backward", "central"]
      debug_print: False
      gradient_method: "openmdao"
    step_size_study: 
      flag: False
    design_of_experiments:
      flag: True
      run_parallel: True
      generator: FullFact # [Uniform, FullFact, PlackettBurman, BoxBehnken, LatinHypercube]
      num_samples: 5 # Number of samples to evaluate model at (Uniform and LatinHypercube only)
      seed: 2
      levels: 5 #  Number of evenly spaced levels between each design variable lower and upper bound (FullFactorial only)
      criterion: None # [None, center, c, maximin, m, centermaximin, cm, correelation, corr]
      iterations: 1
      debug_print: False
  recorder:
    flag: True
    file_name: "recorder.sql"
    includes: ["lcoh", "lcoe"]
